### ISSUE TITLE
0.0.4 update causes Phantom tests to hang

### ISSUE THREAD

**Issue by rlivsey** [miguelcobain/ember-fullscreen#4]
I just updated to v0.0.4 and it causes our Phantomjs tests to hang. 

It just sits there after building until I kill the process.

**Comment by rlivsey** [comment]
I'm heading out now, but if I get a chance I'll dig in tomorrow / over the weekend and see if I can debug further.

**Comment by miguelcobain** [comment]
Very likely closed by https://github.com/miguelcobain/ember-fullscreen/pull/10
Please reopen if issue still present.
