### ISSUE TITLE
Remove autoinjection

### ISSUE THREAD

**Issue by david-duncan** [miguelcobain/ember-fullscreen#7]
I keep reading that autoinjection is an anti-pattern. Are you interested in this as a contribution?

**Comment by miguelcobain** [comment]
Well, ember data does it with its store.
But I kind of agree with that. Do you have any source for "autoinjection is an anti-pattern"? I'm a bit divided, to be honest.

**Comment by david-duncan** [comment]
I haven't seen any claims to performance degradation or any real reason why, but I do know that ember-cli-flash is deprecating it which started to get my attention. Since then I've started to notice a divide in addons which auto inject and which don't

https://github.com/poteto/ember-cli-flash/releases/tag/1.3.12

Maybe @poteto can shed some more light on the exact why.

**Comment by poteto** [comment]
I wouldn't say it's an anti-pattern, but personally I favor explicitness over implicit injection. If you want to use the service in an Ember Object you should explicitly inject it. No reason to have this service available in every single object unless it really needs to. Store is a different story as it does have a valid use in all objects, but personally I would also prefer being explicit with it

IIRC auto injecting the service into all controllers, components routes etc would also require the service to be specified in "needs" in unit tests whether or not it's being used

**Comment by miguelcobain** [comment]
I'm also not a big fan of "magic". @david-duncan I would kindly accept such a contribution.

**Comment by miguelcobain** [comment]
This was closed by https://github.com/miguelcobain/ember-fullscreen/pull/10
