### ISSUE TITLE
using this service for the purposes of the the CSS classing capability only

### ISSUE THREAD

**Issue by SirZach** [miguelcobain/ember-fullscreen#8]
I use ember-fullscreen to go into full-screen mode and it works very nicely. I need the ability to go somewhat full-screen where I toggle the CSS class but without entering full-screen mode. I would love to reuse the service provided to use the `toggle` method but without having to pass in a DOM element. Otherwise, I would need to rewrite a very similar service.

I realize this extends slightly beyond the intended scope of this addon so not expecting to go through, just wanted to see if it was an option. Thanks!

**Comment by miguelcobain** [comment]
So, you need to toggle a css class based on what exactly?

**Comment by SirZach** [comment]
Based on entering a "theatre mode" through some checkbox or toggle.

**Comment by miguelcobain** [comment]
But that theatre mode isn't implemented using html5 fullscreen API?

If I understand your question correctly, you need to share a common boolean to use on templates across your app?

**Comment by SirZach** [comment]
Exactly. Reusing the same boolean to toggle the same class but without using html5 fullscreen API.

**Comment by miguelcobain** [comment]
Something like this?

``` js
// app/services/boolean-service.js
export default Ember.Service.extend({
  value: false,
  toggle() {
    this.toggleProperty('value');
  }
});
```

``` js
// app/controller/route.js
export default Ember.Controller.extend({
  booleanService: Ember.inject.service()
});
```

``` hbs
{{!-- app/templates/routes.hbs --}}
<div class="{{if booleanService.value "its-on-baby" "oh-noes"}}"></div>
```

**Comment by SirZach** [comment]
Yeah, I'm willing to accept that that's what I'll have to do but just wanted to see if you'd be willing to let the service provided by `ember-fullscreen` mimic that behavior since it's in the same realm and toggling the same boolean value.

**Comment by miguelcobain** [comment]
The only way I could see both scenarios share a common solution:
ember-fullscreen could have a way to customise the "fullscreen" implementation.
the default implementation could be using screenful like we do now. But the user could override the implementation with its own.
If we abstract the correct primitives using methods, ember-fullscreen users could inherit the main service and only override the needed fullscreen logic.

It's an idea.

**Comment by SirZach** [comment]
I was thinking maybe something a little simpler. Update `updateEnabled` to accept an override parameter that if exists, uses the value of the supplied argument. It might be muddying the waters a bit too much though.

**Comment by miguelcobain** [comment]
Definitely. I'd use a simple service like in my above comment for something as simple as that.

**Comment by SirZach** [comment]
Which is fine. I just figured it was within the realm of this addon since I need to simply toggle the same exact boolean but no worries. Thanks!
