### ISSUE TITLE
Use npm instead of bower

### ISSUE THREAD

**Issue by rmachielse** [miguelcobain/ember-fullscreen#9]
Hi @miguelcobain 

We are trying to drop our bower dependencies, and this project has come up as an addon that still depends on one.
I could make a pr switching this to npm, however the project seems a bit outdated overall.
What are your plans with this project?

**Comment by miguelcobain** [comment]
@rmachielse I'd love such a PR!

This project didn't have commits in a while, but part of the reason is because of its simplicity and lack of issues. Seems to be working for everyone.
Did you find any outstanding problems?

**Comment by miguelcobain** [comment]
Btw, would be great to remove auto injection as well https://github.com/miguelcobain/ember-fullscreen/issues/7

**Comment by rmachielse** [comment]
Nice, will do!

**Comment by rmachielse** [comment]
And no didn't have any problems either indeed

**Comment by rmachielse** [comment]
@miguelcobain see #10, let me know what you think!

**Comment by miguelcobain** [comment]
@rmachielse that was awesome! Also updated the dummy app and examples.
Released 1.0.0 on npm. 🎉

**Comment by rmachielse** [comment]
@miguelcobain ah I missed a few things, thanks for adding those and the immediate release! 😃 🎉
